### ISSUE TITLE
Bring autocomplete to the vscode

### ISSUE THREAD

**Issue by Hades32** [mat-mcloughlin/vscode-elixir#2]
Thanks for getting Elixir support into VSCode!

How about joining forces with https://github.com/wende/autocomplete-elixir/issues/40 and bring auto-complete as well?

**Comment by philipgiuliani** [comment]
Im also using VSCode now and i'd love to see a better Elixir support in VSCode. Integration for linters, autocomplete. Since VSCode has already good API's for this, it should be pretty easy todo! I would also help where i can.

**Comment by Hades32** [comment]
VSCode recently reached 1.0 and thus should provide a stable API.

**Comment by mat-mcloughlin** [comment]
Hey guys, sorry for the late reply. This repo has laid dormant for a while as I've just not had the time. 

I'm back on it now and keen to get intellisense implemented. I'm busy until the end of next week but should have time to start working on it then

**Comment by philipgiuliani** [comment]
Awesome to hear that! Thanks a lot @mat-mcloughlin!

**Comment by fr1zle** [comment]
Hi @mat-mcloughlin and others,

since I wanted to play around with the vscode API anyway, i started working on autocomplete here:
https://github.com/fr1zle/vscode-elixir/tree/feat/alchemist-server

It uses https://github.com/tonini/alchemist-server (not current master) and is heavily inspired by https://github.com/msaraiva/atom-elixir

Currently the implementation is a bit unstable, but i hope to have it somewhat stable by the end of the week. If you are interested i would then open a (rebased) PR.

**Comment by mat-mcloughlin** [comment]
@fr1zle that's awesome. Going to take a look. But obviously would be very interested

**Comment by Aleksion** [comment]
@fr1zle 
This is an awesome contribution!
But I can't seem to get it to work. I'm really new to elixir, so it might be a beginners error, but what are the prerequisites? I've installed the extension. Created a new mix project. But autocomplete doesn't seem to be working on any of my modules (I have added typespecs to them)

Thank you

**Comment by fr1zle** [comment]
@Aleksion no there should not be any more prerequisites. Could you check in developer tools (Help -> Developer Tools) if there are any errors showing?

**Comment by smt923** [comment]
I was having issues but after reinstalling it seems better now, but is there any way to get all completions instead of just the ones after a first character? The atom extension works like that and I do prefer it, but would much rather use vscode with the same functionality:

[vscode](http://i.imgur.com/HoXnlNX.png)

[atom](http://i.imgur.com/ShxGAGr.png)

**Comment by smt923** [comment]
@fr1zle actually the extension just stopped working for me again, I managed to get a bunch of errors in the console that appear to be related, hopefully it helps reveal something: 

http://pastebin.com/uJ4UZywx

I'm running windows 10 64bit, latest elixir/vscode-elixir/vscode, and node 6.5.0

**Comment by Aleksion** [comment]
@fr1zle - seems like I'm getting the same error as @smt923 
![screen shot 2017-02-16 at 10 12 17](https://cloud.githubusercontent.com/assets/3367641/23014738/7c19aecc-f430-11e6-8371-6375bef3ff08.png)

**Comment by fr1zle** [comment]
Those should all be fixed on the current master. @mat-mcloughlin is master up to date with the extensions store? if not, would you mind publishing?
