### ISSUE TITLE
Atoms (as keys or standalone) have no syntax coloring, they're just white text.

### ISSUE THREAD

**Issue by WildYorkies** [mat-mcloughlin/vscode-elixir#39]
See the example below how `:ok` should be dark blue. Same example you show in your screenshot in the readme. Not sure why it's just white in my editor.

```elixir
myfun = fn
  {:ok, result} -> "hello"
end
```

**Comment by fr1zle** [comment]
It does work when using other color schemes:

![image](https://cloud.githubusercontent.com/assets/311019/21606464/0d7c1646-d1b0-11e6-9f64-2eccc82b99f1.png)

Will try to figure out why that is, though.

**Comment by hoovercj** [comment]
I believe this is because the default themes do not define a color for the token scopes `constant.other.symbol` or `constant.other`.

In vscode 1.9 you can now inspect the scopes that are found for a token (command palette: Inspect TM Scopes) which shows the following (note: it gives the token type and says that no theme selector is being used):

![image](https://cloud.githubusercontent.com/assets/2957173/22650299/dc7b2ef8-ec7e-11e6-89e0-310fda710806.png)

If you look at the [default dark theme](https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_vs.json), you'll see there is no `constant.other.symbol`, only `constant.language`, `constant.regexp`, `constant.numeric`, and the oddly specific `constant.sha.git-rebase`.

The built-in [monokai theme](https://github.com/Microsoft/vscode/blob/master/extensions/theme-monokai/themes/Monokai.tmTheme#L98), on the other hand, has a definition for `constant.other`. And in fact, the inspector shows that it is being used:

![image](https://cloud.githubusercontent.com/assets/2957173/22650564/087b9366-ec80-11e6-9679-134e9b1ff52c.png)

**Comment by WildYorkies** [comment]
Makes sense. Odd that the default it opens with doesn't use a theme for those :/
